name: SonarCloud
on: [push]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Build and test
        run: dotnet build --configuration Release
      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

run: |           
dotnet tool install --global dotnet-coverage           

.\.sonar\scanner\dotnet-sonarscanner begin /k:"vijay7858_hello-world" /o:"vijay7858" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml           
dotnet build --configuration Release          
dotnet-coverage collect 'dotnet test' -f xml -o 'coverage.xml'          
.\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

          

        with:
          args: >
            -Dsonar.organization=vijay7858
            -Dsonar.projectKey=vijay7858_hello-world

